function read_str(f/*:string*/, opts/*:any*/, hint/*:?any*/)/*:Workbook*/ {
	if(hint === 0xFFFE) return csv_to_workbook(f);
	if(f.substr(0, 5) === 'TABLE' && f.substr(0, 12).indexOf('0,1') > -1) return dif_to_workbook(f);
	else if(f.substr(0,2) === 'ID') return sylk_to_workbook(f);
	else if(f.charCodeAt(2) <= 12 && f.charCodeAt(3) <= 31) return dbf_to_workbook(new Buffer(f, 'binary'));
	else if(f.substr(0,19) === 'socialcalc:version:') return socialcalc_to_workbook(f);
	else if(f.substr(0,61) == '# This data file was generated by the Spreadsheet Calculator.') return sc_to_workbook(f);
	else if(f.indexOf(',') != -1 || f.indexOf('\t') != -1) return csv_to_workbook(f);
	else return prn_to_workbook(f);
}

function read_buf(f/*:RawData*/, opts/*:?ParseOpts*/, hint/*:?any*/)/*:Workbook*/ {
	if(f[2] <= 12 && f[3] <= 31) return dbf_to_workbook(f);
	return read_str(f.toString('binary'), opts);
}

function read(f/*:RawData*/, opts/*:?ParseOpts*/, hint/*:?any*/)/*:Workbook*/ {
	if(Buffer.isBuffer(f)) return read_buf(f, opts, hint);
	return read_str(f, opts, hint);
}

var readFile = function (f/*:string*/, o/*:?ParseOpts*/)/*:Workbook*/ {
	var b/*:Buffer*/ = fs.readFileSync(f);
/*
	if(b.length === 0) return null;
*/
	if(((b[0]<<8)|b[1])==0xFFFE) return read_str(cptable.utils.decode(1200, b.slice(2)), o, 0xFFFE);
	return read_buf(b, o);
};
