var read = function (f, opts) {
	if(f.substr(0, 5) === 'TABLE' && f.substr(0, 12).indexOf('0,1') > -1) return dif_to_workbook(f);
	else if(f.substr(0,2) === 'ID') return sylk_to_workbook(f);
	else if(f.substr(0,19) === 'socialcalc:version:') return socialcalc_to_workbook(f);
	else if(f.substr(0,61) == '# This data file was generated by the Spreadsheet Calculator.') return sc_to_workbook(f);
	else if(f.indexOf(',') != -1 || f.indexOf('\t') != -1) return csv_to_workbook(f);
	else return prn_to_workbook(f);
};

var readFile = function (f, o) {
	var b = fs.readFileSync(f);
	if(((b[0]<<8)|b[1])==0xFFFE) return read(cptable.utils.decode(1200, b.slice(2)), o);
	return read(b.toString(), o);
};
